server:
  port: 8080
  
  servlet:
    context-path: /Statistics
    
spring:  datasource:    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test_python?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:  mapper-locations:  - classpath:mapping/*Mapper.xml
  type-aliases-package: com.jsl.Statistics.entities
  

debug: false

logging:
  path: D:/log/
  level: 
    com.jsl.Statistics.controller: info
    com.jsl.Statistics.entities: debug